test(complex): add complex project obfuscation test

diff --git a/.github/workflows/mac-tests.yml b/.github/workflows/mac-tests.yml
--- a/.github/workflows/mac-tests.yml
+++ b/.github/workflows/mac-tests.yml
@@ -62,6 +62,57 @@ jobs:
                   path: |
                       pyguard
 
+    obfuscation-complex-macos:
+        name: Complex Obfuscation MacOS
+        needs: ["build"]
+        runs-on: macos-latest
+
+        steps:
+            - name: Check out code from GitHub
+              uses: actions/checkout@v7
+
+            - name: Set up Python
+              uses: actions/setup-python@v7
+              with:
+                  python-version: "3.14"
+
+            - name: Install dependencies
+              run: |
+                  python3 -m pip install --upgrade pip
+                  pip3 install -r requirements.txt
+
+            - name: Download Executable
+              uses: actions/download-artifact@v8
+              with:
+                  name: pyguard-macos_${{ needs.build.outputs.sha_short }}
+                  path: "examples"
+
+            - name: Preparation For Test
+              working-directory: examples
+              run: |
+                  mv pyguard complex/
+                  chmod +x complex/pyguard
+                  rm -rf complex/obfuscated
+
+            - name: Obfuscation Test
+              working-directory: examples/complex
+              run: |
+                  ./pyguard obfuscate --aes --hashdata --fernet --chacha --salsa --base64 --recursive 4 --follow-imports --no-input --files proxy.py --dirs dir main.py
+
+            - name: Testing Results
+              working-directory: examples/complex/obfuscated
+              run: |
+                  OUTPUT=$(python main.py)
+                  echo "Output: $OUTPUT"
+
+                  echo "Result: "
+                  if [ "$OUTPUT" = "hello world" ]; then
+                    echo "Success: main.py output contains 'hello world'"
+                  else
+                    echo "Failure: main.py output does not contain 'hello world'"
+                    exit 1
+                  fi
+
     obfuscation-multifile-macos:
         name: Multi-file Obfuscation MacOS
         needs: ["build"]
@@ -152,6 +203,57 @@ jobs:
 
             - name: Testing Results
               working-directory: examples/onefile/obfuscated
+              run: |
+                  OUTPUT=$(python main.py)
+                  echo "Output: $OUTPUT"
+
+                  echo "Result: "
+                  if [ "$OUTPUT" = "hello world" ]; then
+                    echo "Success: main.py output contains 'hello world'"
+                  else
+                    echo "Failure: main.py output does not contain 'hello world'"
+                    exit 1
+                  fi
+
+    obfuscationlegacy-complex-macos:
+        name: Complex Legacy Obfuscation MacOS
+        needs: ["build"]
+        runs-on: macos-latest
+
+        steps:
+            - name: Check out code from GitHub
+              uses: actions/checkout@v7
+
+            - name: Set up Python
+              uses: actions/setup-python@v7
+              with:
+                  python-version: "3.14"
+
+            - name: Install dependencies
+              run: |
+                  python3 -m pip install --upgrade pip
+                  pip3 install -r requirements.txt
+
+            - name: Download Executable
+              uses: actions/download-artifact@v8
+              with:
+                  name: pyguard-macos_${{ needs.build.outputs.sha_short }}
+                  path: "examples"
+
+            - name: Preparation For Test
+              working-directory: examples
+              run: |
+                  mv pyguard complex-legacy/
+                  chmod +x complex-legacy/pyguard
+                  rm -rf complex-legacy/obfuscated
+
+            - name: Obfuscation Test
+              working-directory: examples/complex-legacy
+              run: |
+                  ./pyguard obfuscatelegacy --no-input --mode 4 --loops 6 --dirs dir --files main.py,proxy.py
+
+            - name: Testing Results
+              working-directory: examples/complex-legacy/obfuscated
               run: |
                   OUTPUT=$(python main.py)
                   echo "Output: $OUTPUT"
diff --git a/.github/workflows/win-tests.yml b/.github/workflows/win-tests.yml
--- a/.github/workflows/win-tests.yml
+++ b/.github/workflows/win-tests.yml
@@ -64,6 +64,60 @@ jobs:
                   path: |
                       pyguard.exe
 
+    obfuscation-complex:
+        name: Complex Obfuscation Windows
+        needs: ["build"]
+        runs-on: windows-latest
+
+        steps:
+            - name: Check out code from GitHub
+              uses: actions/checkout@v7
+
+            - name: Set up Python
+              uses: actions/setup-python@v7
+              with:
+                  python-version: "3.14"
+
+            - name: Install dependencies
+              shell: bash
+              run: |
+                  python3 -m pip install --upgrade pip
+                  pip3 install -r requirements.txt
+
+            - name: Download Executable
+              uses: actions/download-artifact@v8
+              with:
+                  name: pyguard-win_${{ needs.build.outputs.sha_short }}
+                  path: "examples"
+
+            - name: Preparation For Test
+              working-directory: examples
+              shell: bash
+              run: |
+                  mv pyguard.exe complex/
+                  rm -rf complex/obfuscated
+
+            - name: Obfuscation Test
+              working-directory: examples/complex
+              shell: bash
+              run: |
+                  ./pyguard obfuscate --aes --hashdata --fernet --chacha --salsa --base64 --recursive 4 --follow-imports --no-input --files proxy.py --dirs dir main.py
+
+            - name: Testing Results
+              working-directory: examples/complex/obfuscated
+              shell: bash
+              run: |
+                  OUTPUT=$(python main.py)
+                  echo "Output: $OUTPUT"
+
+                  echo "Result: "
+                  if [ "$OUTPUT" = "hello world" ]; then
+                    echo "Success: main.py output contains 'hello world'"
+                  else
+                    echo "Failure: main.py output does not contain 'hello world'"
+                    exit 1
+                  fi
+
     obfuscation-multifile:
         name: Multi-file Obfuscation Windows
         needs: ["build"]
@@ -159,6 +213,60 @@ jobs:
 
             - name: Testing Results
               working-directory: examples/onefile/obfuscated
+              shell: bash
+              run: |
+                  OUTPUT=$(python main.py)
+                  echo "Output: $OUTPUT"
+
+                  echo "Result: "
+                  if [ "$OUTPUT" = "hello world" ]; then
+                    echo "Success: main.py output contains 'hello world'"
+                  else
+                    echo "Failure: main.py output does not contain 'hello world'"
+                    exit 1
+                  fi
+
+    obfuscationlegacy-complex:
+        name: Complex Legacy Obfuscation Windows
+        needs: ["build"]
+        runs-on: windows-latest
+
+        steps:
+            - name: Check out code from GitHub
+              uses: actions/checkout@v7
+
+            - name: Set up Python
+              uses: actions/setup-python@v7
+              with:
+                  python-version: "3.14"
+
+            - name: Install dependencies
+              shell: bash
+              run: |
+                  python3 -m pip install --upgrade pip
+                  pip3 install -r requirements.txt
+
+            - name: Download Executable
+              uses: actions/download-artifact@v8
+              with:
+                  name: pyguard-win_${{ needs.build.outputs.sha_short }}
+                  path: "examples"
+
+            - name: Preparation For Test
+              working-directory: examples
+              shell: bash
+              run: |
+                  mv pyguard.exe complex-legacy/
+                  rm -rf complex-legacy/obfuscated
+
+            - name: Obfuscation Test
+              working-directory: examples/complex-legacy
+              shell: bash
+              run: |
+                  ./pyguard obfuscatelegacy --no-input --mode 4 --loops 6 --dirs dir --files main.py,proxy.py
+
+            - name: Testing Results
+              working-directory: examples/complex-legacy/obfuscated
               shell: bash
               run: |
                   OUTPUT=$(python main.py)
